version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      EXPIRED_JWT_TOKEN: ${EXPIRED_JWT_TOKEN}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      EXPIRED_JWT_REFRESH_TOKEN: ${EXPIRED_JWT_REFRESH_TOKEN}
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - app_data:/app

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple-erp
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      CLOUDFLARE_TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
  app_data:
