version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - app_data:/app   # gunakan volume docker

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple-erp
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    ports:
      - "4040:4040"
    env_file:
      - .env
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - backend
    

networks:
  backend:

volumes:
  db_data:
  app_data:
